/*
 * This source file was generated by the Gradle 'init' task
 */
package org.kotlinrpg

fun main() {
    // println(
    //     """
    //                x
    //     .-. _______|
    //     |=|/     /  \
    //     | |_____|_""_|
    //     |_|_[X]_|____|
    //     """.trimIndent(),
    //)
    //

    val game = Game()
    game.startGameLoop()
}
